### ISSUE TITLE
unclear: tests that have been included in WASI

### ISSUE THREAD

**Issue by emielvanseveren** [WebAssembly/wasi-testsuite#23]
The readme states the following: "The repository only holds tests that have been included in the WASI, and it does not include tests for in-progress proposals or other experimental APIs". Aren't all the current interfaces in phase 1 and 2, so in-progress proposals?  Is this the current snapshot?

**Comment by loganek** [comment]
Hi @emielvanseveren, I think the description might not be accurate enough; what it means is that tests cover the API defined in the [current snapshot](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md). Would you mind updating the README file?

Many thanks
