### ISSUE TITLE
Move logic in .github/workflows/compile-tests.yml  to Makefile

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wasi-testsuite#43]
Right now, the compilation steps are defined outside the scope of the test runner, and executing them is copy/paste from `.github/workflows/compile-tests.yml`.

What I would love to see instead is:

`make install` - runs the python install as needed
`make compile` - compiles all the various things
`make test` - runs `python3 test-runner/wasi_test_runner.py`
`make` default does install, compile, test which prevents out-of-date steps.

Lacking this causes unnecessary glitches. For example, I ran compilation manually earlier and forgot the steps needed. The source of one file changed, though the old binary was present. Specifically, the test changed expectations of exit code 1 to 33.

One the makefile is together, integrators like me can have an easier time, and the GitHub part is simpler as it just calls targets vs very explicit step implementations.

**Comment by codefromthecrypt** [comment]
renamed as the issue was about drift

**Comment by loganek** [comment]
Hi @codefromthecrypt , I think it makes sense to have build script defined outside of the github workflow. I'm quite interested in your usecase though - runtimes should use precompiled WASM binaries from `prod/testsuite-base` branch so they won't have to install the toolchain and compile the code by themselves. Is that something that'd work better for you?

**Comment by codefromthecrypt** [comment]
@loganek that works for me as long as I don't need to change the sources (only consume the resulting wasm), which is currently the case. I think if I started contributing tests, it would be less errorpone to have a makefile, but for now all good!

**Comment by loganek** [comment]
No problem; just for reference, there's a PR for integrating testsuite with WAMR: https://github.com/bytecodealliance/wasm-micro-runtime/pull/1832
