### ISSUE TITLE
Add rust tests to README and testsuite-base branch

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wasi-testsuite#49]
Looks like rust tests have been added, but instructions don't include them (should they?) also, the wasm isn't uploaded to the testsuite-base branch. Is this intentional or just a TODO?

https://github.com/WebAssembly/wasi-testsuite/tree/prod/testsuite-base/tests/rust

**Comment by loganek** [comment]
Thanks for spotting that, I updated the code: https://github.com/WebAssembly/wasi-testsuite/pull/54
