### ISSUE TITLE
Daily runtime validation is only running C tests

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wasi-testsuite#60]
#55 adds the wazero adapter which passes assemblyscript, c and rust tests. I noticed that the existing runs are only showing the C tests. Is there a glitch in the setup?

https://github.com/WebAssembly/wasi-testsuite/actions/runs/4298591707/jobs/7492869631

**Comment by evacchi** [comment]
I think the syntax being use there is incorrect, it should not pass `-t` multiple times

**Comment by eloparco** [comment]
> I think the syntax being use there is incorrect, it should not pass -t multiple times

Yes, I was already pushing a fix. The repeated `-t` seems to be the problem.

**Comment by loganek** [comment]
The fix was already merged, thanks.
